---
kind: pipeline
type: kubernetes
name: cnj-rest-build

steps:
#  - name: downstream-commit-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    privileged: true
#    commands:
#      - start-docker.sh
#      - mvn clean deploy -f cnj-rest-downstream-spring/pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: downstream-integration-test-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    commands:
#      - mvn clean verify -f cnj-rest-downstream-spring/pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: javaee-commit-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    privileged: true
#    commands:
#      - start-docker.sh
#      - mvn clean deploy -f cnj-rest-backend-javaee/pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: javaee-integration-test-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    commands:
#      - mvn clean verify -f cnj-rest-backend-javaee/pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: micro-commit-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    privileged: true
#    commands:
#      - start-docker.sh
#      - mvn clean deploy -f cnj-rest-backend-micro/pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: micro-integration-test-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    privileged: true
#    commands:
#      - start-docker.sh
#      - mvn clean verify -f cnj-rest-backend-micro/pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: spring-commit-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    privileged: true
#    commands:
#      - start-docker.sh
#      - mvn clean deploy -f cnj-rest-backend-spring/pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
#  - name: spring-integration-test-stage
#    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
#    commands:
#      - mvn clean verify -f cnj-rest-backend-spring/pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
  - name: quarkus-commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
    privileged: true
    commands:
      - start-docker.sh
      - mvn clean deploy -f cnj-rest-backend-quarkus/pom.xml -B -ff -e -V -U -P commit-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
  - name: quarkus-integration-test-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build:1.1.0
    commands:
      - mvn clean verify -f cnj-rest-backend-quarkus/pom.xml -B -ff -e -V -U -P integration-test-stage -Dchangelist=.${DRONE_BRANCH} -Dsha1=.${DRONE_COMMIT_SHA:0:8}
